"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.version = exports.help = exports.clone = exports.set_url = exports.start = void 0;
var start_1 = require("../commands/start");
Object.defineProperty(exports, "start", { enumerable: true, get: function () { return start_1.start; } });
var set_url_1 = require("../commands/set_url");
Object.defineProperty(exports, "set_url", { enumerable: true, get: function () { return set_url_1.set_url; } });
var clone_1 = require("../commands/clone");
Object.defineProperty(exports, "clone", { enumerable: true, get: function () { return clone_1.clone; } });
var help_1 = require("../commands/help");
Object.defineProperty(exports, "help", { enumerable: true, get: function () { return help_1.help; } });
var version_1 = require("../commands/version");
Object.defineProperty(exports, "version", { enumerable: true, get: function () { return version_1.version; } });
